---
# this playbook builds a hubot server over node.js
- hosts: default
  tasks:
  - name: update apt's cache
    sudo: yes
    apt: update-cache=yes cache_valid_time=3600

  - name: fetch and install redis
    sudo: yes
    apt: name=redis-server
      state=present

  - name: tweak the redis config file
    sudo: yes
    lineinfile: dest=/etc/redis/redis.conf regexp='^timeout' line="timeout 300"

  - name: start redis
    sudo: yes
    service: name=redis-server enabled=yes state=started

  - name: redis is responding?
    command: redis-cli PING

  - name: specify node source repo
    sudo: yes
    script: ./files/set-node-source-repo.sh

  - name: fetch and install node
    sudo: yes
    apt: name=nodejs
      state=present

  - name: node is responding?
    command: node -v

