---
# A list of tasty fruits
- hosts: default
  tasks:
  - name: apt update for cache
    sudo: yes
    apt: name=redis-server
      state=present
#      update-cache=yes

  - name: tweak the redis config file
    sudo: yes
    lineinfile: dest=/etc/redis/redis.conf regexp='^timeout' line="timeout 300"

  - name: start redis
    sudo: yes
    service: name=redis-server state=started
